[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://simple-landing-page.azurewebsites.net/api"
  status = 200
  force = true